### ISSUE TITLE
The trace datasets are unavailable

### ISSUE THREAD

**Issue by PureWhiteWu** [moka-rs/mokabench#12]
Dropbox shows that all three files are not available.
Could you please upload those files to the repo(maybe using git-lfs?)

https://www.dropbox.com/sh/9ii9sc7spcgzrth/z9qaItlfnw/Papers/ARCTraces/DS1.lis

**Comment by PureWhiteWu** [comment]
Or is there any other way I can get those datasets?
Thanks!

**Comment by tatsuya6502** [comment]
Hi. For now, I put all the ARC datasets I have to an Amazon S3 bucket. Please download them from here: ~~https://arc-ds-2023.s3.ap-northeast-1.amazonaws.com/arc-dataset.txz (49.5 MB)~~ (Deleted. See [this comment](https://github.com/moka-rs/mokabench/issues/12#issuecomment-1684926710) for the new location)

Then expand the `txz`:

```console
## NOTE: You might need to install `xz` (xz-utils) in addition to 
## `tar` to expand a `txz` file.

$ tar xf arc-dataset.txz
```

Later, I will put them to a (new?) Git repository with git-lfs.

I am redistributing them with a permission from Dr. Dharmendra S. Modha, a coauthor of the ARC papers. I contacted Dr. Modha after seeing your message last night, and he kindly allowed me to publish them with a reference to ARC papers.

A referent to an ARC paper:

> [Nimrod Megiddo](http://theory.stanford.edu/~megiddo/bio.html) and [Dharmendra S. Modha](https://researcher.watson.ibm.com/researcher/view_person_subpage.php?id=4700), "ARC: A Self-Tuning, Low Overhead Replacement Cache," _USENIX Conference on File and Storage Technologies (FAST 03), San Francisco, CA_, pp. 115-130, March 31-April 2, 2003.

I do not have some of the datasets such as `ConCat.lis`. If I remember correctly, their download links were already broken when I tried to download few year ago. Anyway, the above `arc-dataset.txz` should have enough stuff to get started.

Also note that current version of `moka` has a large hard-coded buffer ([diagram](https://github.com/moka-rs/moka/wiki#admission-and-eviction-policies)). So you should avoid to test `moka` with smaller datasets such as `OLTP.lis` (11 MB), otherwise you will get a skewed result with very high cache hit rate as the entire dataset may fit into the buffer.

**Comment by PureWhiteWu** [comment]
Thank you very much for this!

**Comment by tatsuya6502** [comment]
FYI, I moved the trace files here: https://github.com/moka-rs/cache-trace/tree/main/arc
